spring:
  server:
    error:
    include-message: always
    include-binding-errors: always
  datasource:
    url: jdbc:mysql://localhost:3306/auto_parts?createDatabaseIfNotExist=true
    application:
      yml:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


